### ISSUE TITLE
Emror

### ISSUE THREAD

**Issue by CAF-ID** [zhwzein/Killua-Zoldyck#2]
1. Abis Scan Nemu Error
TypeError: Cannot read properties of undefined (reading 'find')
    at /storage/emulated/0/Killua/killua.js:44:96
    at Array.find (<anonymous>)
    at module.exports (/storage/emulated/0/Killua/killua.js:44:76)
TypeError: Cannot read properties of undefined (reading 'find')
    at /storage/emulated/0/Killua/killua.js:44:96
    at Array.find (<anonymous>)
    at module.exports (/storage/emulated/0/Killua/killua.js:44:76)
TypeError: Cannot read properties of undefined (reading 'find')
    at /storage/emulated/0/Killua/killua.js:44:96
    at Array.find (<anonymous>)
    at module.exports (/storage/emulated/0/Killua/killua.js:44:76)
TypeError: Cannot read properties of undefined (reading 'find')
    at /storage/emulated/0/Killua/killua.js:44:96
    at Array.find (<anonymous>)
    at module.exports (/storage/emulated/0/Killua/killua.js:44:76)
2. Pas Error Yang Nomor Satu, trus run ulang ga ada keluar error ny tapi ga respon

**Comment by zhwzein** [comment]
fix
