### ISSUE TITLE
.emoji command error

### ISSUE THREAD

**Issue by Cosm1cBug** [zhwzein/Killua-Zoldyck#65]
C:\Users\aru\OneDrive\Desktop\Killua-Zoldyck\node_modules\node-webpmux\parser.js:41
    if (buf === undefined) { throw new Error('Reached end while reading header'); }
                                   ^

Error: Reached end while reading header
    at WebPReader.readFileHeader (C:\Users\aru\OneDrive\Desktop\Killua-Zoldyck\node_modules\node-webpmux\parser.js:41:36)
    at async WebPReader.read (C:\Users\aru\OneDrive\Desktop\Killua-Zoldyck\node_modules\node-webpmux\parser.js:147:58)
    at async Image.load (C:\Users\aru\OneDrive\Desktop\Killua-Zoldyck\node_modules\node-webpmux\webp.js:192:17)
    at async writeExif (C:\Users\aru\OneDrive\Desktop\Killua-Zoldyck\lib\Sticker.js:136:9)
    at async WAConnection.sendFile (C:\Users\aru\OneDrive\Desktop\Killua-Zoldyck\lib\Simple.js:133:24)
'w' is not recognized as an internal or external command,
operable program or batch file.

**Comment by zhwzein** [comment]
cek ffmpeg installed or not
